services:
  - type: web
    name: collectiviq-mcp
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: CIQ_API_KEY
        value: ciq_live_gpmadb2w9Sy8dymaQkTlUQzRufiYTvH0E7emhFrSR8RA
      - key: PORT
        generateValue: false
        value: "10000"
